module Cerebrum_core{

    /**
    * Module containing all errors raised by Gro.
    */
    module Errors{

        /**
        * Error raised when trying to fetch elements
        * from an empty iterator.
        * \param explanation A string containing a short explanation.
        */
        exception IteratorEmptyError{
            string explanation;
        };

        /**
        * Error raised when trying to fetch a class type which does
        * not exist in Cerebrum.
        * \param explanation A string containing a short explanation.
        */
        exception NoSuchTypeError{
            string explanation;
        };

        /**
        * Error raised when commiting changes in APHandler.
        * Not used yet!
        * \param explanation A string containing a short explanation.
        */
        exception CommitError{
            string explanation;
        };

        /**
        * Error raised when trying to fetch a node wich dont exists.
        * \param explanation A string containing a short explanation.
        */
        exception NoSuchNodeError{
            string explanation;
        };

        /**
        * Error raised when trying to lock a node wich is already locked
        * for reading or for writing.
        * \param explanation A string containing a short explanation.
        */
        exception AlreadyLockedError{
            string explanation;
        };

        /**
        * Error raised when trying to writelock without obtaining a
        * readlock first.
        * \param explanation A string containing a short explanation.
        */
        exception NotLockedError{
            string explanation;
        };

        /**
        * Error raised when trying to get/set an node attribute wich
        * dont exists.
        * \param explanation A string containing a short explanation
        */
        exception NoSuchAttributeError{
            string explanation;
        };

        /**
        * Error raised when trying to write an attribute wich is only readable.
        * \param explanation A string containing a short explanation
        */
        exception ReadOnlyAttributeError{
            string explanation;
        };

        /**
        * Error raised when the server creates an error. In other words, when
        * the PROGRAMMER writes crappy code!
        * \param explanation A string containing a short explanation
        */
        exception ServerError{
            string explanation;
        };

    };
};
