/*
 * Copyright 2004, 2005 University of Oslo, Norway
 *
 * This file is part of Cerebrum.
 *
 * Cerebrum is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * Cerebrum is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Cerebrum; if not, write to the Free Software Foundation,
 * Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
 */

module Cerebrum_core{

    /**
    * Module containing all errors raised by Gro.
    */
    module Errors{

        /**
        * Error raised when trying to fetch elements
        * from an empty iterator.
        * \param explanation A string containing a short explanation.
        */
        exception IteratorEmptyError{
            string explanation;
        };

        /**
        * Error raised when trying to fetch a class type which does
        * not exist in Cerebrum.
        * \param explanation A string containing a short explanation.
        */
        exception NoSuchTypeError{
            string explanation;
        };

        /**
        * Error raised when commiting changes in APHandler.
        * Not used yet!
        * \param explanation A string containing a short explanation.
        */
        exception CommitError{
            string explanation;
        };

        /**
        * Error raised when trying to fetch a node wich dont exists.
        * \param explanation A string containing a short explanation.
        */
        exception NoSuchNodeError{
            string explanation;
        };

        /**
        * Error raised when trying to lock a node wich is already locked
        * for reading or for writing.
        * \param explanation A string containing a short explanation.
        */
        exception AlreadyLockedError{
            string explanation;
        };

        /**
        * Error raised when trying to writelock without obtaining a
        * readlock first.
        * \param explanation A string containing a short explanation.
        */
        exception NotLockedError{
            string explanation;
        };

        /**
        * Error raised when trying to get/set an node attribute wich
        * dont exists.
        * \param explanation A string containing a short explanation
        */
        exception NoSuchAttributeError{
            string explanation;
        };

        /**
        * Error raised when trying to write an attribute wich is only readable.
        * \param explanation A string containing a short explanation
        */
        exception ReadOnlyAttributeError{
            string explanation;
        };

        /**
        * Error raised when the server creates an error. In other words, when
        * the PROGRAMMER writes crappy code!
        * \param explanation A string containing a short explanation
        */
        exception ServerError{
            string explanation;
        };

        /**
        * Error raised by a transaction. The exact failure will be in the
        * explanation string
        */
        exception TransactionError{
            string explanation;
        };

        /**
        * Error raised when trying to get a search class from an unsearchable class.
        */
        exception UnsearchableClassError{
            string explanation;
        };

        /**
        * Error raised when a search fails.
        */
        exception SearchError{
            string explanation;
        };

        /**
        * Error raised during login.
        */
        exception LoginError{
            string explanation;
        };

        /**
        * Error raised when no result can be returned
        */
        exception NotFoundError{
            string explanation;
        };
    };
};
