# -*- coding: iso-8859-1 -*-
# Copyright 2013 University of Oslo, Norway
#
# This file is part of Cerebrum.
#
# Cerebrum is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Cerebrum is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Cerebrum; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.

"""Country code constants with Norwegian translation"""

# See contrib/countrycode/

from Cerebrum import Constants
from Cerebrum.Constants import _CountryCode

class CountryConstants(Constants.Constants):
    country_bd = _CountryCode("BD", "Bangladesh", "880", "Bangladesh")
    country_be = _CountryCode("BE", "Belgium", "32", "Belgia")
    country_bf = _CountryCode("BF", "Burkina Faso", "226", "Burkina Faso")
    country_bg = _CountryCode("BG", "Bulgaria", "359", "Bulgaria")
    country_ba = _CountryCode("BA", "Bosnia and Herzegovina", "387", "Bosnia-Hercegovina")
    country_bb = _CountryCode("BB", "Barbados", "1-246", "Barbados")
    country_wf = _CountryCode("WF", "Wallis and Futuna Islands", "681", "Wallis- og Futunaøyene")
    country_bl = _CountryCode("BL", "Saint Barthélemy", "590", "Saint-Barthélemy")
    country_bm = _CountryCode("BM", "Bermuda", "1-441", "Bermuda")
    country_bn = _CountryCode("BN", "Brunei Darussalam", "673", "Brunei")
    country_bo = _CountryCode("BO", "Bolivia", "591", "Bolivia")
    country_bh = _CountryCode("BH", "Bahrain", "973", "Bahrain")
    country_bi = _CountryCode("BI", "Burundi", "257", "Burundi")
    country_bj = _CountryCode("BJ", "Benin", "229", "Benin")
    country_bt = _CountryCode("BT", "Bhutan", "975", "Bhutan")
    country_jm = _CountryCode("JM", "Jamaica", "1-876", "Jamaica")
    country_bv = _CountryCode("BV", "Bouvet Island", "47", "Bouvetøya")
    country_bw = _CountryCode("BW", "Botswana", "267", "Botswana")
    country_ws = _CountryCode("WS", "Samoa", "685", "Samoa")
    country_bq = _CountryCode("BQ", "Bonaire, Sint Eustatius and Saba", "599", "Bonaire, Sint Eustatius og Saba")
    country_br = _CountryCode("BR", "Brazil", "55", "Brasil")
    country_bs = _CountryCode("BS", "Bahamas", "1-242", "Bahamas")
    country_je = _CountryCode("JE", "Jersey", "44", "Jersey")
    country_by = _CountryCode("BY", "Belarus", "375", "Hviterussland")
    country_bz = _CountryCode("BZ", "Belize", "501", "Belize")
    country_ru = _CountryCode("RU", "Russian Federation", "7", "Russland")
    country_rw = _CountryCode("RW", "Rwanda", "250", "Rwanda")
    country_rs = _CountryCode("RS", "Serbia", "381", "Serbia")
    country_tl = _CountryCode("TL", "Timor-Leste", "670", "Øst-Timor")
    country_re = _CountryCode("RE", "Reunion", "262", "Réunion")
    country_pa = _CountryCode("PA", "Panama", "507", "Panama")
    country_lr = _CountryCode("LR", "Liberia", "231", "Liberia")
    country_ro = _CountryCode("RO", "Romania", "40", "Romania")
    country_tk = _CountryCode("TK", "Tokelau", "690", "Tokelau")
    country_gw = _CountryCode("GW", "Guinea-Bissau", "245", "Guinea-Bissau")
    country_gu = _CountryCode("GU", "Guam", "1-671", "Guam")
    country_gt = _CountryCode("GT", "Guatemala", "502", "Guatemala")
    country_gs = _CountryCode("GS", "South Georgia and South Sandwich Islands", "500", "Sør-Georgia og de søre Sandwichøyene")
    country_gr = _CountryCode("GR", "Greece", "30", "Hellas")
    country_gq = _CountryCode("GQ", "Equatorial Guinea", "240", "Ekvatorial-Guinea")
    country_gp = _CountryCode("GP", "Guadeloupe", "590", "Guadeloupe")
    country_jp = _CountryCode("JP", "Japan", "81", "Japan")
    country_gy = _CountryCode("GY", "Guyana", "592", "Guyana")
    country_gg = _CountryCode("GG", "Guernsey", "44", "Guernsey")
    country_gf = _CountryCode("GF", "French Guiana", "594", "Fransk Guyana")
    country_ge = _CountryCode("GE", "Georgia", "995", "Georgia")
    country_gd = _CountryCode("GD", "Grenada", "1-473", "Grenada")
    country_gb = _CountryCode("GB", "United Kingdom", "44", "Storbritannia")
    country_ga = _CountryCode("GA", "Gabon", "241", "Gabon")
    country_pk = _CountryCode("PK", "Pakistan", "92", "Pakistan")
    country_gn = _CountryCode("GN", "Guinea", "224", "Guinea")
    country_gm = _CountryCode("GM", "Gambia", "220", "Gambia")
    country_gl = _CountryCode("GL", "Greenland", "299", "Grønland")
    country_gi = _CountryCode("GI", "Gibraltar", "350", "Gibraltar")
    country_gh = _CountryCode("GH", "Ghana", "233", "Ghana")
    country_om = _CountryCode("OM", "Oman", "968", "Oman")
    country_jo = _CountryCode("JO", "Jordan", "962", "Jordan")
    country_hr = _CountryCode("HR", "Croatia", "385", "Kroatia")
    country_ht = _CountryCode("HT", "Haiti", "509", "Haiti")
    country_kn = _CountryCode("KN", "Saint Kitts and Nevis", "1-869", "Saint Kitts og Nevis")
    country_hk = _CountryCode("HK", "Hong Kong", "852", "Hongkong")
    country_hn = _CountryCode("HN", "Honduras", "504", "Honduras")
    country_hm = _CountryCode("HM", "Heard and McDonald Islands", "672", "Heard- og McDonald-øyene")
    country_ve = _CountryCode("VE", "Venezuela", "58", "Venezuela")
    country_pr = _CountryCode("PR", "Puerto Rico", "1", "Puerto Rico")
    country_ps = _CountryCode("PS", "Palestine", "970", "De okkuperte palestinske områdene")
    country_pw = _CountryCode("PW", "Palau", "680", "Palau")
    country_pt = _CountryCode("PT", "Portugal", "351", "Portugal")
    country_sj = _CountryCode("SJ", "Svalbard and Jan Mayen Islands", "47", "Svalbard og Jan Mayen")
    country_py = _CountryCode("PY", "Paraguay", "595", "Paraguay")
    country_iq = _CountryCode("IQ", "Iraq", "964", "Irak")
    country_lv = _CountryCode("LV", "Latvia", "371", "Latvia")
    country_pf = _CountryCode("PF", "French Polynesia", "689", "Fransk Polynesia")
    country_pg = _CountryCode("PG", "Papua New Guinea", "675", "Papua Ny-Guinea")
    country_pe = _CountryCode("PE", "Peru", "51", "Peru")
    country_kw = _CountryCode("KW", "Kuwait", "965", "Kuwait")
    country_ph = _CountryCode("PH", "Philippines", "63", "Filippinene")
    country_pn = _CountryCode("PN", "Pitcairn", "870", "Pitcairn")
    country_pl = _CountryCode("PL", "Poland", "48", "Polen")
    country_pm = _CountryCode("PM", "Saint Pierre and Miquelon", "508", "Saint-Pierre-et-Miquelon")
    country_zm = _CountryCode("ZM", "Zambia", "260", "Zambia")
    country_eh = _CountryCode("EH", "Western Sahara", "212", "Vest-Sahara")
    country_ee = _CountryCode("EE", "Estonia", "372", "Estland")
    country_eg = _CountryCode("EG", "Egypt", "20", "Egypt")
    country_za = _CountryCode("ZA", "South Africa", "27", "Sør-Afrika")
    country_ec = _CountryCode("EC", "Ecuador", "593", "Ecuador")
    country_it = _CountryCode("IT", "Italy", "39", "Italia")
    country_vn = _CountryCode("VN", "Vietnam", "84", "Vietnam")
    country_sb = _CountryCode("SB", "Solomon Islands", "677", "Salomonøyene")
    country_et = _CountryCode("ET", "Ethiopia", "251", "Etiopia")
    country_zw = _CountryCode("ZW", "Zimbabwe", "263", "Zimbabwe")
    country_sa = _CountryCode("SA", "Saudi Arabia", "966", "Saudi-Arabia")
    country_es = _CountryCode("ES", "Spain", "34", "Spania")
    country_er = _CountryCode("ER", "Eritrea", "291", "Eritrea")
    country_me = _CountryCode("ME", "Montenegro", "382", "Montenegro")
    country_md = _CountryCode("MD", "Moldova", "373", "Moldova")
    country_mg = _CountryCode("MG", "Madagascar", "261", "Madagaskar")
    country_mf = _CountryCode("MF", "Saint Martin (French part)", "590", "Saint-Martin")
    country_ma = _CountryCode("MA", "Morocco", "212", "Marokko")
    country_mc = _CountryCode("MC", "Monaco", "377", "Monaco")
    country_uz = _CountryCode("UZ", "Uzbekistan", "998", "Usbekistan")
    country_mm = _CountryCode("MM", "Myanmar", "95", "Burma")
    country_ml = _CountryCode("ML", "Mali", "223", "Mali")
    country_mo = _CountryCode("MO", "Macau", "853", "Macao")
    country_mn = _CountryCode("MN", "Mongolia", "976", "Mongolia")
    country_mh = _CountryCode("MH", "Marshall Islands", "692", "Marshalløyene")
    country_us = _CountryCode("US", "United States of America", "1", "USA")
    country_mu = _CountryCode("MU", "Mauritius", "230", "Mauritius")
    country_mt = _CountryCode("MT", "Malta", "356", "Malta")
    country_mw = _CountryCode("MW", "Malawi", "265", "Malawi")
    country_mv = _CountryCode("MV", "Maldives", "960", "Maldivene")
    country_mq = _CountryCode("MQ", "Martinique", "596", "Martinique")
    country_mp = _CountryCode("MP", "Northern Mariana Islands", "1-670", "Nord-Marianene")
    country_ms = _CountryCode("MS", "Montserrat", "1-664", "Montserrat")
    country_mr = _CountryCode("MR", "Mauritania", "222", "Mauritania")
    country_im = _CountryCode("IM", "Isle of Man", "44", "Man")
    country_ug = _CountryCode("UG", "Uganda", "256", "Uganda")
    country_tz = _CountryCode("TZ", "Tanzania", "255", "Tanzania")
    country_ua = _CountryCode("UA", "Ukraine", "380", "Ukraina")
    country_mx = _CountryCode("MX", "Mexico", "52", "Mexico")
    country_at = _CountryCode("AT", "Austria", "43", "Østerrike")
    country_fr = _CountryCode("FR", "France", "33", "Frankrike")
    country_aw = _CountryCode("AW", "Aruba", "297", "Aruba")
    country_sh = _CountryCode("SH", "Saint Helena", "290", "St. Helena")
    country_lu = _CountryCode("LU", "Luxembourg", "352", "Luxembourg")
    country_dm = _CountryCode("DM", "Dominica", "1-767", "Dominica")
    country_fi = _CountryCode("FI", "Finland", "358", "Finland")
    country_fj = _CountryCode("FJ", "Fiji", "679", "Fiji")
    country_fk = _CountryCode("FK", "Falkland Islands", "500", "Falklandsøyene")
    country_fm = _CountryCode("FM", "Micronesia", "691", "Mikronesiaføderasjonen")
    country_fo = _CountryCode("FO", "Faroe Islands", "298", "Færøyene")
    country_ni = _CountryCode("NI", "Nicaragua", "505", "Nicaragua")
    country_nl = _CountryCode("NL", "Netherlands", "31", "Nederland")
    country_no = _CountryCode("NO", "Norway", "47", "Norge")
    country_na = _CountryCode("NA", "Namibia", "264", "Namibia")
    country_vu = _CountryCode("VU", "Vanuatu", "678", "Vanuatu")
    country_nc = _CountryCode("NC", "New Caledonia", "687", "Ny-Caledonia")
    country_ne = _CountryCode("NE", "Niger", "227", "Niger")
    country_nf = _CountryCode("NF", "Norfolk Island", "672", "Norfolk Island")
    country_ng = _CountryCode("NG", "Nigeria", "234", "Nigeria")
    country_nz = _CountryCode("NZ", "New Zealand", "64", "New Zealand")
    country_np = _CountryCode("NP", "Nepal", "977", "Nepal")
    country_nr = _CountryCode("NR", "Nauru", "674", "Nauru")
    country_nu = _CountryCode("NU", "Niue", "683", "Niue")
    country_ck = _CountryCode("CK", "Cook Islands", "682", "Cookøyene")
    country_ci = _CountryCode("CI", "Côte d'Ivoire", "225", "Elfenbenskysten")
    country_ch = _CountryCode("CH", "Switzerland", "41", "Sveits")
    country_co = _CountryCode("CO", "Colombia", "57", "Colombia")
    country_cn = _CountryCode("CN", "China", "86", "Kina")
    country_cm = _CountryCode("CM", "Cameroon", "237", "Kamerun")
    country_cl = _CountryCode("CL", "Chile", "56", "Chile")
    country_cc = _CountryCode("CC", "Cocos (Keeling) Islands", "61", "Kokosøyene")
    country_ca = _CountryCode("CA", "Canada", "1", "Canada")
    country_cg = _CountryCode("CG", "Congo (Brazzaville)", "242", "Kongo-Brazzaville")
    country_cf = _CountryCode("CF", "Central African Republic", "236", "Den sentralafrikanske republikk")
    country_cd = _CountryCode("CD", "Congo (Kinshasa)", "243", "Kongo")
    country_cz = _CountryCode("CZ", "Czech Republic", "420", "Tsjekkia")
    country_cy = _CountryCode("CY", "Cyprus", "357", "Kypros")
    country_cx = _CountryCode("CX", "Christmas Island", "61", "Christmasøya")
    country_cr = _CountryCode("CR", "Costa Rica", "506", "Costa Rica")
    country_hu = _CountryCode("HU", "Hungary", "36", "Ungarn")
    country_cw = _CountryCode("CW", "Curaçao", "", "Curaçao")
    country_cv = _CountryCode("CV", "Cape Verde", "238", "Kapp Verde")
    country_cu = _CountryCode("CU", "Cuba", "53", "Cuba")
    country_sz = _CountryCode("SZ", "Swaziland", "268", "Swaziland")
    country_sy = _CountryCode("SY", "Syria", "963", "Syria")
    country_sx = _CountryCode("SX", "Sint Maarten", "", "Sint Maarten")
    country_kg = _CountryCode("KG", "Kyrgyzstan", "996", "Kirgisistan")
    country_ke = _CountryCode("KE", "Kenya", "254", "Kenya")
    country_ss = _CountryCode("SS", "South Sudan", "211", "Sør-Sudan")
    country_sr = _CountryCode("SR", "Suriname", "597", "Surinam")
    country_ki = _CountryCode("KI", "Kiribati", "686", "Kiribati")
    country_kh = _CountryCode("KH", "Cambodia", "855", "Kambodsja")
    country_sv = _CountryCode("SV", "El Salvador", "503", "El Salvador")
    country_km = _CountryCode("KM", "Comoros", "269", "Komorene")
    country_st = _CountryCode("ST", "Sao Tome and Principe", "239", "São Tomé og Príncipe")
    country_sk = _CountryCode("SK", "Slovakia", "421", "Slovakia")
    country_kr = _CountryCode("KR", "Korea, South", "82", "Sør-Korea")
    country_si = _CountryCode("SI", "Slovenia", "386", "Slovenia")
    country_kp = _CountryCode("KP", "Korea, North", "850", "Nord-Korea")
    country_so = _CountryCode("SO", "Somalia", "252", "Somalia")
    country_sn = _CountryCode("SN", "Senegal", "221", "Senegal")
    country_sm = _CountryCode("SM", "San Marino", "378", "San Marino")
    country_sl = _CountryCode("SL", "Sierra Leone", "232", "Sierra Leone")
    country_sc = _CountryCode("SC", "Seychelles", "248", "Seychellene")
    country_kz = _CountryCode("KZ", "Kazakhstan", "7", "Kasakhstan")
    country_ky = _CountryCode("KY", "Cayman Islands", "1-345", "Caymanøyene")
    country_sg = _CountryCode("SG", "Singapore", "65", "Singapore")
    country_se = _CountryCode("SE", "Sweden", "46", "Sverige")
    country_sd = _CountryCode("SD", "Sudan", "249", "Sudan")
    country_do = _CountryCode("DO", "Dominican Republic", "", "Den dominikanske republikk")
    country_dj = _CountryCode("DJ", "Djibouti", "253", "Djibouti")
    country_dk = _CountryCode("DK", "Denmark", "45", "Danmark")
    country_vg = _CountryCode("VG", "Virgin Islands, British", "1-284", "Jomfruøyene (Britisk)")
    country_de = _CountryCode("DE", "Germany", "49", "Tyskland")
    country_ye = _CountryCode("YE", "Yemen", "967", "Jemen")
    country_dz = _CountryCode("DZ", "Algeria", "213", "Algerie")
    country_mk = _CountryCode("MK", "Macedonia", "389", "Makedonia")
    country_uy = _CountryCode("UY", "Uruguay", "598", "Uruguay")
    country_yt = _CountryCode("YT", "Mayotte", "262", "Mayotte")
    country_um = _CountryCode("UM", "United States Minor Outlying Islands", " ", "USA, mindre, utenforliggende øyer")
    country_lb = _CountryCode("LB", "Lebanon", "961", "Libanon")
    country_lc = _CountryCode("LC", "Saint Lucia", "1-758", "Saint Lucia")
    country_la = _CountryCode("LA", "Laos", "856", "Laos")
    country_tv = _CountryCode("TV", "Tuvalu", "688", "Tuvalu")
    country_tw = _CountryCode("TW", "Taiwan", "886", "Taiwan")
    country_tt = _CountryCode("TT", "Trinidad and Tobago", "1-868", "Trinidad og Tobago")
    country_tr = _CountryCode("TR", "Turkey", "90", "Tyrkia")
    country_lk = _CountryCode("LK", "Sri Lanka", "94", "Sri Lanka")
    country_li = _CountryCode("LI", "Liechtenstein", "423", "Liechtenstein")
    country_tn = _CountryCode("TN", "Tunisia", "216", "Tunisia")
    country_to = _CountryCode("TO", "Tonga", "676", "Tonga")
    country_lt = _CountryCode("LT", "Lithuania", "370", "Litauen")
    country_tm = _CountryCode("TM", "Turkmenistan", "993", "Turkmenistan")
    country_tj = _CountryCode("TJ", "Tajikistan", "992", "Tadsjikistan")
    country_ls = _CountryCode("LS", "Lesotho", "266", "Lesotho")
    country_th = _CountryCode("TH", "Thailand", "66", "Thailand")
    country_tf = _CountryCode("TF", "French Southern Lands", "262", "Søre franske territorier")
    country_tg = _CountryCode("TG", "Togo", "228", "Togo")
    country_td = _CountryCode("TD", "Chad", "235", "Tsjad")
    country_tc = _CountryCode("TC", "Turks and Caicos Islands", "1-649", "Turks- og Caicosøyene")
    country_ly = _CountryCode("LY", "Libya", "218", "Libya")
    country_va = _CountryCode("VA", "Vatican City", "39-06", "Vatikanstaten")
    country_vc = _CountryCode("VC", "Saint Vincent and the Grenadines", "1-784", "Saint Vincent og Grenadinene")
    country_ae = _CountryCode("AE", "United Arab Emirates", "971", "De forente arabiske emirater")
    country_ad = _CountryCode("AD", "Andorra", "376", "Andorra")
    country_ag = _CountryCode("AG", "Antigua and Barbuda", "1-268", "Antigua og Barbuda")
    country_af = _CountryCode("AF", "Afghanistan", "93", "Afghanistan")
    country_ai = _CountryCode("AI", "Anguilla", "1-264", "Anguilla")
    country_vi = _CountryCode("VI", "Virgin Islands, U.S.", "1-340", "Jomfruøyene (USA)")
    country_is = _CountryCode("IS", "Iceland", "354", "Island")
    country_ir = _CountryCode("IR", "Iran", "98", "Iran")
    country_am = _CountryCode("AM", "Armenia", "374", "Armenia")
    country_al = _CountryCode("AL", "Albania", "355", "Albania")
    country_ao = _CountryCode("AO", "Angola", "244", "Angola")
    country_aq = _CountryCode("AQ", "Antarctica", "672", "Antarktis")
    country_as = _CountryCode("AS", "American Samoa", "1-684", "Amerikansk Samoa")
    country_ar = _CountryCode("AR", "Argentina", "54", "Argentina")
    country_au = _CountryCode("AU", "Australia", "61", "Australia")
    country_il = _CountryCode("IL", "Israel", "972", "Israel")
    country_io = _CountryCode("IO", "British Indian Ocean Territory", "246", "Britisk territorium i Indiahavet")
    country_in = _CountryCode("IN", "India", "91", "India")
    country_ax = _CountryCode("AX", "Åland", "358", "Åland")
    country_az = _CountryCode("AZ", "Azerbaijan", "994", "Aserbajdsjan")
    country_ie = _CountryCode("IE", "Ireland", "353", "Irland")
    country_id = _CountryCode("ID", "Indonesia", "62", "Indonesia")
    country_my = _CountryCode("MY", "Malaysia", "60", "Malaysia")
    country_qa = _CountryCode("QA", "Qatar", "974", "Qatar")
    country_mz = _CountryCode("MZ", "Mozambique", "258", "Mosambik")
