#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import re
import sys
import getopt
import os

from Cerebrum.Utils import Factory
from import_dns import FileParsers
header_splitter = '; AUTOGENERATED: do not edit below this line\n'

def strip_zone_file(fname, outfname):
    parser = FileParsers()
    parser.prepare_parse_zone_file(fname)
    p = os.popen("sort > %s" % outfname, 'w')
    while True:
        dta = parser.next_zone_entry()
        if not dta:
            break
        if dta[0] != 'contact':
            p.write(str((parser.owner, dta[:-1]))+"\n")
    p.close()

def strip_reverse_file(fname, outfname):
    p = os.popen("sort > %s" % outfname, 'w')
    parser = FileParsers()
    parser.prepare_parse_revmap(fname)
    while True:
        dta = parser.next_revmap()
        if not dta:
            break
        p.write(str(dta)+"\n")
    p.close()

def usage(exitcode=0):
    print """Usage: [options]

    Convert the file to a format suitable for 'diff -u'.

    --help: help
    -i filename: input filename
    -o filename: output filename
    -z convert zonefile
    -r convert reverse map
    -Z | --zone-def name: a dns_zone.name entry
    """
    sys.exit(exitcode)

def main():
    global zone
    try:
        opts, args = getopt.getopt(sys.argv[1:], 'Z:i:o:zr', [
            'help',])
    except getopt.GetoptError:
        usage(1)
    if not opts:
        usage(1)

    db = Factory.get('Database')()
    co = Factory.get('Constants')(db)
    for opt, val in opts:
        if opt in ('--help', ):
            usage()
        elif opt in ('-i',):
            infile = val
        elif opt in ('-o',):
            outfile = val
        elif opt in ('-z',):
            strip_zone_file(infile, outfile)
        elif opt in ('--zone-def', '-Z'):
            zone = co.DnsZone(val)
            int(zone) # Trigger error if missing
            FileParsers.set_zone(zone)
        elif opt in ('-r',):
            strip_reverse_file(infile, outfile)

if __name__ == '__main__':
    main()

# arch-tag: 59315bb1-74c4-44b3-b43d-498cf1e0b799
