#!/bin/bash -x

# Collection of scripts for common tasks while tsting at UiO.  Will be
# removed/converted once we near a stable implementation.

new_db() {
    # /local/opt/postgresql/bin/dropdb -U cerebrum cerebrum_dns
    # /local/opt/postgresql/bin/createdb -U cerebrum -E unicode cerebrum_dns

    # Trenger egentlig ikke alle disse tabellene, men ønsker å slipe å
    # klå på CLASS_CONSTANTS
    ./makedb.py --extra-file=design/bofhd_tables.sql --extra-file=design/bofhd_auth.sql --extra-file=design/mod_posix_user.sql --extra-file=design/mod_changelog.sql --extra-file=design/mod_stedkode.sql --extra-file=design/mod_email.sql --extra-file=design/mod_lt.sql --extra-file=design/mod_printer_quota.sql --extra-file=design/mod_dns.sql

}

build_maps() {
    time ./contrib/dns/build_zone.py --head /cerebrum/etc/cerebrum/dns/129.240.head -m 129.240.0.0/16 -r data/129.240.new
    time ./contrib/dns/build_zone.py --head /cerebrum/etc/cerebrum/dns/uio.no.static_head --head /cerebrum/etc/cerebrum/dns/uio.no.head -Z uio -b data/uio.no.new
    time ./contrib/dns/generate_nismaps.py --group_spread NIS_mng@uio --user_spread NIS_user@uio -n data/netgroup.host.new || true
    time ./contrib/dns/build_zone.py --head /cerebrum/etc/cerebrum/dns/129.240.head -m 158.36.184.0/24 -r data/158.36.184.new
}

migrate_uio() {
    # nukes existing dns data, end re-imports them
    ./makedb.py --drop design/mod_dns.sql || true
    ./contrib/dns/test_utils.py --del
    ./makedb.py design/mod_dns.sql 

    set -e
    echo "Du må ha kjørt fetch_src_files, renamet filene til *.orig"
    echo "og lagt inn linja"
    echo "; AUTOGENERATED: do not edit below this line"
    echo "på rett plass i begge filene for at dette skal virke"
    # uio.no : "Før MX records for Organizational units" linja
    # 129.240 : etter NS linjene

    if [ ! -e data/129.240.orig.cmp ]; then
	./contrib/dns/strip4cmp.py -Z uio -i data/129.240.orig -o data/129.240.orig.cmp -r
	./contrib/dns/strip4cmp.py -Z uio -i data/uio.no.orig -o data/uio.no.orig.cmp -z
    fi

    time ./contrib/dns/import_dns.py -Z uio -z data/uio.no.orig -h data/hosts.orig -i
    time ./contrib/dns/import_dns.py -r data/129.240.orig -r data/158.36.184.orig -r data/158.36.191.orig
    time ./contrib/dns/import_dns.py -Z uio --netgroups data/netgroup.host.orig -n

    build_maps
    ./contrib/dns/strip4cmp.py -Z uio -i data/129.240.new -o data/129.240.new.cmp -r
    ./contrib/dns/strip4cmp.py -Z uio -i data/uio.no.new -o data/uio.no.new.cmp -z

    echo diff -u data/129.240.orig.cmp data/129.240.new.cmp
    echo diff -u data/uio.no.orig.cmp data/uio.no.new.cmp 
}

fetch_src_files() {
    set -e
    mkdir tmpdns
    cd tmpdns
    scp nissen:/site/bind9/pz/{uio.no,129.240,158.36.191,158.36.184} .
    scp cerebellum:/cerebrum/yp/src/hosts cerebellum:/cerebrum/yp/src/netgroup.host .
    tar czf uio-zone-`date '+%Y-%m-%d'`.tgz *
}

case "$1" in
    --migrate)
	migrate_uio
	;;
    --new-db)
	new_db
	;;
    --fetch)
	fetch_src_files
	;;
    *)
	echo "Usage: old_and_large.sh --migrate | --fetch | --new-db"
	;;
esac

# arch-tag: dfc54693-f7c1-4c6a-b97c-a0f3450b3696
