#!/bin/sh

# Copyright 2003 University of Oslo, Norway
#
# This file is part of Cerebrum.
#
# Cerebrum is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Cerebrum is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Cerebrum; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.

# Create homedir for new users, and copy files to the directory.
# Optionally sourcing pre and post scripts

PATH=/bin:/usr/bin:/local/bin:/etc:/usr/ucb:/usr/etc:/usr/bsd
export PATH
umask 066			# drwx--x--x

uname="$1"
homedir="$2"
uid="$3"
gid="$4"
tpldir="$5"
scriptdir="$6"
fullname="$7"

if [ -f "$scriptdir/mkhomedir.pre" ]; then
   . "$scriptdir/mkhomedir.pre"
fi

mkdir "$homedir"
# The "/." suffix is needed to cope with $tpldir being a symlink.
cp -rp "$tpldir/." "$homedir"
chown -R "$uid" "$homedir"
chgrp -R "$gid" "$homedir"

if [ -f "$scriptdir/mkhomedir.post" ]; then
   . "$scriptdir/mkhomedir.post"
fi

# arch-tag: 8e6c4093-4fa0-4902-b5ad-86e52c246464
