#!/bin/bash
#
#
#
# Small script to tag cerebrum branches
#
#
#
shopt -s extglob


base_url=https://cerebrum.svn.sourceforge.net/svnroot/cerebrum

die() {
    echo "$1"
    exit "${2:-1}"
}

usage() {
    cat << EOF
Usage:$0 [-m commit_message] branch [tag]

    -m commit_message   Set a specific commit-message. Default is "Tagging 
                        <tag> from <branch>."
    -h|--help           Print this message and exit.

    Examples:
    Create a new tag of branch 2.2
        $0 2.2
    Create a specific tag of branch 2.2
        $0 2.2 2.2.57
EOF

    exit "${1:-0}"
}

while [[ $1 = -* ]]; do
    case $1 in 
        -m) commit_msg=$2; shift;;
        -h|--help) usage;;
    esac
    shift
done
[[ $1 = -- ]] && shift
branch=$1 tag=$2

[[ $branch ]] || die "Missing branch version" 1
if [[ -z $tag ]]; then
    echo "Querying server to find next tag-number..."
    greatest=0
    while IFS= read -r dir; do
        [[ $dir = "ntnu-prod-$branch".+([0-9])/ ]] || continue
        tagnum=${dir%/} tagnum=${tagnum##*.}
        (( greatest = tagnum > greatest ? tagnum : greatest ))
    done < <(svn list "$base_url/tags")
    tag=$branch.$((greatest + 1))
fi

urls=( "$base_url/branches/ntnu-prod-$branch" "$base_url/tags/ntnu-prod-$tag" )
commit_msg=${commit_msg:-Tagging $tag from $branch}
command=( 
    svn copy 
    -m "$commit_msg"
    "$base_url/branches/ntnu-prod-$branch"
    "$base_url/tags/ntnu-prod-$tag"
)

echo "Going to perform the following command:"
printf "%q " "${command[@]}"; printf '\n'
echo "Hit Enter or Return to continue, Ctrl-c to abort"
read || die "Aborted" 2
"${command[@]}"
