#!/bin/bash
cd /src
pip install -r requirements.txt
pip install -r testsuite/ansible_docker/test-requirements.txt
python setup.py install
cd /src/testsuite/ansible_docker
ansible-playbook -i inventory.cfg setup_cerebrum.yml --tags "common"
ansible-playbook -i inventory.cfg setup_cerebrum.yml --tags $ANSIBLE_TAG \
--extra-vars "crb_db_name=${ANSIBLE_TAG} crb_db_host=${DB_HOST}"
py.test --cov=/src --cov-report xml:/src/testresults/${ANSIBLE_TAG}_coverage.xml \
            --junitxml=/src/testresults/${ANSIBLE_TAG}_junit.xml \
            $(cat /src/testsuite/ansible_docker/roles/${ANSIBLE_TAG}/files/pytest_tests.txt)