#! /bin/bash
#
# script for starting cerebrum's bofhd


start() {
	echo -n $"Starting bofhd: "
        /cerebrum/sbin/bofhd.py -c /cerebrum/etc/cerebrum/config.dat -p 8000
	echo 

}






# arch-tag: 3fe990e8-b42c-11da-976b-0fa7c0b8e378
